# Generated by Django 4.0.1 on 2022-08-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='EurobetCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EurobetQuoteTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoldbetCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoldbetQuoteTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetcoinCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetcoinQuoteTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SnaiCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SnaiQuoteTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StanleybetCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StanleybetQuoteTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StanleybetEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stanleybetcompetitions')),
            ],
        ),
        migrations.CreateModel(
            name='StanleybetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stanleybetevents')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stanleybetquotetypes')),
            ],
        ),
        migrations.CreateModel(
            name='SnaiEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.snaicompetitions')),
            ],
        ),
        migrations.CreateModel(
            name='SnaiEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.snaievents')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.snaiquotetypes')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetcoinEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.planetcoincompetitions')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetcoinEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.planetcoinevents')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.planetcoinquotetypes')),
            ],
        ),
        migrations.CreateModel(
            name='GoldbetEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.goldbetcompetitions')),
            ],
        ),
        migrations.CreateModel(
            name='GoldbetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.goldbetevents')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.goldbetquotetypes')),
            ],
        ),
        migrations.CreateModel(
            name='EurobetEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.eurobetcompetitions')),
            ],
        ),
        migrations.CreateModel(
            name='EurobetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quote', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.eurobetevents')),
                ('qt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.eurobetquotetypes')),
            ],
        ),
    ]
