version: '3'
services:
  nginx:
    restart: always
    build: 
      context: ./nginx
    container_name: webserver
    image: "nginx:1.15-alpine"
    depends_on: 
      - webapp
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  webapp:
    restart: always
    build:
      context: ./
    # command: bash -c "gunicorn --config gunicorn-cfg.py core.wsgi"
    command: bash -c "gunicorn -b 0.0.0.0:8000 -k gevent --worker-tmp-dir /dev/shm core.wsgi:application"
    container_name: webapp
    volumes:
      - .:/topbet
    ports:
      - '8000:8000'
    cpus: 2.0
    mem_reservation: "10M"
    mem_limit: "3584M"
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf/:/etc/letsencrypt