version: '3'
services:
  appseed-app:
    container_name: app
    restart: always
    env_file: .env
    build: .
    networks:
      - web_network
    command: bash -c "gunicorn --config gunicorn-cfg.py core.wsgi"
    cpus: 2.0
    mem_reservation: "10M"
    mem_limit: "3584M"
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  web_network:
    driver: bridge
 