version: '3'
services:
  topbet-app:
    container_name: app
    restart: always
    build: 
      context: ./
    command: bash -c "gunicorn --config gunicorn-cfg.py core.wsgi"
    volumes:
      - .:/topbet
    ports:
      - 8000:8000
    cpus: 2.0
    mem_reservation: "10M"
    mem_limit: "3584M"
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - app