# Generated by Django 4.0.1 on 2022-09-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EurobetCompetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EurobetEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EurobetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EurobetQuoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldbetCompetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldbetEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldbetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldbetQuoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetwinCompetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetwinEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetwinEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanetwinQuoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnaiCompetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnaiEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnaiEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SnaiQuoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StanleybetCompetition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pal', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StanleybetEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.DateTimeField(null=True)),
                ('fast_code', models.IntegerField(null=True)),
                ('avv', models.IntegerField(null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stanleybetcompetition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StanleybetQuoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StanleybetEventQuote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.JSONField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.stanleybetevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='stanleybetcompetition',
            index=models.Index(fields=['name'], name='quote_stanl_name_de35c9_idx'),
        ),
        migrations.AddField(
            model_name='snaieventquote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.snaievent'),
        ),
        migrations.AddField(
            model_name='snaievent',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.snaicompetition'),
        ),
        migrations.AddIndex(
            model_name='snaicompetition',
            index=models.Index(fields=['name'], name='quote_snaic_name_6109c0_idx'),
        ),
        migrations.AddField(
            model_name='planetwineventquote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.planetwinevent'),
        ),
        migrations.AddField(
            model_name='planetwinevent',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.planetwincompetition'),
        ),
        migrations.AddIndex(
            model_name='planetwincompetition',
            index=models.Index(fields=['name'], name='quote_plane_name_231e26_idx'),
        ),
        migrations.AddField(
            model_name='goldbeteventquote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.goldbetevent'),
        ),
        migrations.AddField(
            model_name='goldbetevent',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.goldbetcompetition'),
        ),
        migrations.AddIndex(
            model_name='goldbetcompetition',
            index=models.Index(fields=['name'], name='quote_goldb_name_93b734_idx'),
        ),
        migrations.AddField(
            model_name='eurobeteventquote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.eurobetevent'),
        ),
        migrations.AddField(
            model_name='eurobetevent',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.eurobetcompetition'),
        ),
        migrations.AddIndex(
            model_name='eurobetcompetition',
            index=models.Index(fields=['name'], name='quote_eurob_name_657c33_idx'),
        ),
        migrations.AddIndex(
            model_name='stanleybetevent',
            index=models.Index(fields=['name'], name='quote_stanl_name_09581e_idx'),
        ),
        migrations.AddIndex(
            model_name='snaievent',
            index=models.Index(fields=['name'], name='quote_snaie_name_e099eb_idx'),
        ),
        migrations.AddIndex(
            model_name='planetwinevent',
            index=models.Index(fields=['name'], name='quote_plane_name_fd889c_idx'),
        ),
        migrations.AddIndex(
            model_name='goldbetevent',
            index=models.Index(fields=['name'], name='quote_goldb_name_cab624_idx'),
        ),
        migrations.AddIndex(
            model_name='eurobetevent',
            index=models.Index(fields=['name'], name='quote_eurob_name_8b9730_idx'),
        ),
    ]
